Task #8
anraf1001/object-oriented-programming pull request #17
Opened 2020-06-17 15:24 UTC by Vicx95

2020-06-17 15:50 UTC, arafalski requested changes

2020-06-17 15:50 UTC, anraf1001 commented on shm/inc/ship.hpp
> +#include <vector>
```suggestion
#include "cargo.hpp"

#include <string>
#include <vector>
```

2020-06-17 16:12 UTC, arafalski submitted a review, later dismissed

2020-06-17 16:47 UTC, kontrybutor commented on shm/inc/player.hpp
> +    size_t calculateavailableSpace();
```suggestion
    size_t getAvailableSpace();
```
or `calculateAvailableSpace()`

2020-06-17 16:47 UTC, kontrybutor commented on shm/src/player.cpp
> +    return freeSpace;
What do you think about:

```suggestion
size_t reservedSpace = std::accumulate(
    ship_->getAllCargo().begin(),
    ship_->getAllCargo().end(),
    0,
    [](size_t space, const Cargo& cargo) {
        return space += cargo.getAmount();
    });
size_t availableSpace = ship_->getCapacity() - reservedSpace;
```

Sorry for formatting :)

2020-06-17 19:56 UTC, piezol requested changes

2020-06-17 19:56 UTC, piezol commented on shm/inc/ship.hpp
> +    std::vector<Cargo>& getallCargo() { return cargo_; }
Do we really need to make our whole cargo vector effectively public in Ship?
Idea:
In Ship a public function, that returns the available space (use solution @kontrybutor suggested).
In Player - just call that function.

2020-06-18 05:12 UTC, anraf1001 commented on shm/src/ship.cpp
> +}
New line

2020-06-18 11:00 UTC, arafalski approved these changes

2020-06-18 11:24 UTC, kontrybutor approved these changes

2020-06-18 11:25 UTC, merged